server:
  port: 8083
spring:
  application:
    name: apigw
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      enabled: true
      routes:
      - id: customer
        uri: lb://CUSTOMER
        predicates:
        - Path=/api/v1/customers/**
      globalcors:
        cors-configurations:
         '[/**]':
          allowedOrigins: "http://localhost:3000"
          allowedHeaders: "*"
          allowedMethods:
            - GET
            - POST
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka